FROM ubuntu:20.04

ARG DEBIAN_FRONTEND="noninteractive"

RUN apt-get update -qq && apt-get install -qq -y \
  autoconf \
  automake \
  build-essential \
  cmake \
  libfreetype6-dev \
  libtool \
  pkg-config \
  texinfo \
  wget \
  yasm \
  nasm \
  zlib1g-dev \
  libnuma-dev \
  git \
  libx264-dev \
  libx265-dev \
  libopus-dev \
  libmp3lame-dev \
  libfdk-aac-dev \
  libvpx-dev \
  python3-setuptools \
  python3-pip \
  python3-venv \
  libc6 \
  libc6-dev \
  unzip \
  libnuma1 \
  libunistring-dev libaom-dev \
  libnuma-dev \
  && rm -rf /var/lib/apt/lists/*

RUN mkdir /nvenc
WORKDIR /nvenc
RUN git clone https://git.videolan.org/git/ffmpeg/nv-codec-headers.git
RUN cd nv-codec-headers && make install


COPY ./docker/install_ffmpeg.sh /install_ffmpeg.sh
RUN chmod +x /install_ffmpeg.sh && \
  /install_ffmpeg.sh && \
  cp /root/bin/ffmpeg /usr/local/bin/ffmpeg && \
  cp /root/bin/ffprobe /usr/local/bin/ffprobe

COPY . /processing-chain

WORKDIR /processing-chain

RUN pip3 install --no-cache-dir -r requirements.txt
RUN pip3 install git+https://github.com/bitmovin/bitmovin-python.git@v1.21.0
ENV NAME pnats_processing_chain
RUN mkdir /proponent-databases
