apiVersion: batch/v1
kind: Job
metadata:
  name: proc-example-gpu
spec:
  template: 
    metadata:
      name: proc-example-gpu
      labels:
        ailab-job-type: batch
        project: pnats-video-proc
    spec: 
      containers:
      - name: proc-container
        command: ["/bin/bash", "-c"]
        image: /foo/bar/pnats-video-proc/main/davids_videocoding/processing-chain:2.3.3_gpu
        args: ["python3 p01_generateSegments.py --verbose -c /proj/pnats-video-proc/procchain-gamingtest/example-databases/P2SXM00/P2SXM00.yaml"]
        #args: ["bufferer -i /proj/pnats-video-proc/procchain-gamingtest/example-databases/P2SXM00/avpvs/P2STR00_SRC000_HRC000_concat_wo_buffer.avi -o /proj/pnats-video-proc/procchain-gamingtest/example-databases/P2SXM00/avpvs/P2STR00_SRC000_HRC000.avi -b [[1,1.1],[5,0.334],[6,0.1667]] --force-framerate --black-frame -v ffv1 -a pcm_s16le -x yuv422p10le -e --skipping"]
        #args: ["ffmpeg -video_size 1920x1080 -framerate 60 -i /proj/pnats-video-proc/gamingvideos/yuvs/R5Apex_30.yuv -c:v hevc_nvenc -tag:v hvc1 -crf 20 -an /proj/pnats-video-proc/gamingvideos/testout_nvenc_2.mp4"]
        resources:
          requests:
            memory: "4Gi"
            cpu: "2"
            nvidia.com/gpu: 8
          limits:
            memory: "4Gi"
            cpu: "2"
            nvidia.com/gpu: 8
      tolerations:
        - key: nvidia.com/gpu
          operator: "Exists"
          effect: NoSchedule
      imagePullSecrets:
        - name: registrysecretprocchain
      restartPolicy: Never
  backoffLimit: 1
